name: Task Management
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: https://todo-server-one.vercel.app/api/update?id=BmGTr8yqlhZOsd3sWN9T6heuwuI2&project=data-structures&username=d-liya
          method: POST
